experiment:
  seed: 88
  save_dir: ../experiments/
data:
  annotations: ../data/train_kfold.csv
  data_dir: ../data/
  input: filename
  target: level
  outer_fold: 0
  inner_fold: null
  dataset:
    name: ImageDataset
    params:
      flip: true
      verbose: true
transform:
  resize:
    name: resize_ignore
    params:
      imsize: [384, 384]
  crop:
    null
  augment:
    name: grayscale_augment
    params:
      n: 3
      p: 0.9
  preprocess: 
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]
task:
  name: ClassificationTask
  params: null
model:
  name: Net2D
  params:
    backbone: swin_base_patch4_window12_384
    pretrained: true
    num_classes: 5
    dropout: 0.2
    in_channels: 3
    multisample_dropout: true
loss:
  name: CrossEntropyLoss
  params: null
optimizer:
  name: AdamW
  params:
    lr: 0.0003
    weight_decay: 0.0005
scheduler:
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-06
train:
  batch_size: 32
  num_epochs: 10
evaluate:
  metrics:
  - Kappa
  monitor: kappa
  mode: max
