experiment:
  seed: 88
  save_dir: ../experiments/
data:
  annotations: ../data/aptos/train_without_300_kfold.csv
  data_dir: ../data/aptos/train_images/
  input: filename
  target: diagnosis
  outer_fold: 0
  inner_fold: null
  dataset:
    name: ImageDataset
    params:
      flip: true
      verbose: true
transform:
  resize:
    name: resize_ignore
    params:
      imsize: [512, 512]
  crop:
    null
  augment:
    name: grayscale_augment
    params:
      n: 3
      p: 1.0
  preprocess: 
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]
task:
  name: ClassificationTask
  params: null
model:
  name: Net2D
  load_pretrained: ../experiments/mk000/sbn/fold0/checkpoints/last.ckpt
  params:
    backbone: tf_efficientnet_b6_ns
    pretrained: true
    num_classes: 5
    dropout: 0.5
    in_channels: 3
    multisample_dropout: true
loss:
  name: CrossEntropyLoss
  params: null
optimizer:
  name: AdamW
  params:
    lr: 0.0003
    weight_decay: 0.0005
scheduler:
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-06
train:
  batch_size: 16
  num_epochs: 5
evaluate:
  metrics:
  - Kappa
  monitor: kappa
  mode: max
